### ISSUE TITLE
Question about the go.csv

### ISSUE THREAD

**Issue by fw0325** [turbine-ai/PerturbSeqPredBenchmark#1]
Thank you very much for your work, it is very good. 
I have a question about go.csv, is it the same file as the go_v1.csv in bulk_models.ipynb? When I run the _get_go_features() function in bulk_models.ipynb, it shows that there are some perturbations in the adamson and norman dataset that are not in go_pca.index. How can I solve this problem?

**Comment by weizhiting** [comment]
Hi, Have you solved the question? @fw0325.  i met the same issue.

**Comment by fw0325** [comment]
> Hi, Have you solved the question? @fw0325. i met the same issue.

No，no one replied to me. I tried setting the values ​​of non-existent genes to 0 in GO, but the results of the bulk model are not as good as the paper.

**Comment by geroldcsendes** [comment]
Hi @fw0325  and @weizhiting. Thanks for your interest in our work! I am terribly sorry, somehow the github notifications got turned off for this repo. Let me look at this and get back to you asap!

**Comment by geroldcsendes** [comment]
I pushed a commit that replaces the `go_v1.csv` with `go.csv`. This contains the non-existent genes as well. I can reproduce the results of the paper. Could you take a look?

**Comment by fw0325** [comment]
> I pushed a commit that replaces the `go_v1.csv` with `go.csv`. This contains the non-existent genes as well. I can reproduce the results of the paper. Could you take a look?

The issue has been addressed. Thank you!
